version: "3.1"
services:
  api:
    container_name: aot_wiki_api
    stdin_open: true
    tty: true

    env_file:
      - .env
      - .env.dev

    image: limebrewofficial/attack-on-titan-wiki-api:${AOT_WIKI_API_VERSION}
    
    ##?Expose port
    ports:
      - ${AOT_WIKI_API_PORT}:${AOT_WIKI_API_PORT}

    depends_on:
      - db

  db:
    #? Set container name
    container_name: aot_wiki_db
    image: mongo:latest

    #? Restart if down
    restart: always

    #? Environment file
    env_file:
        - .env

    #? Ports
    ports:
        - ${AOT_WIKI_DB_PORT}:${AOT_WIKI_DB_PORT}