version: "3.1"
services:
  api:
    container_name: aot_wiki_api
    stdin_open: true
    tty: true

    env_file:
      - .env

    #Build from current directory
    build:
      context: .
      dockerfile: Dockerfile

    image: saptak619/aot_wiki_api:${AOT_WIKI_API_VERSION}

    entrypoint: uvicorn server:app --host 0.0.0.0 --port ${AOT_WIKI_API_PORT} --workers 3 --reload

    #Expose port
    ports:
      - ${AOT_WIKI_API_PORT}:${AOT_WIKI_API_PORT}
