name: Build and push AOT-wiki to DockerHub

on: 
  push: 
    branches: [main]

jobs: 
  build_push: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout into main
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Grab the current version of the service
        run: |
          VER=$( grep AOT_WIKI_API_VERSION .env | cut -f 2 -d "=" | tr "\"" "\n")
          echo "USERNAME=limebrewofficial" >> $GITHUB_ENV
          echo "VERSION=$VER" >> $GITHUB_ENV
          echo "REPO=attack-on-titan-wiki-api" >> $GITHUB_ENV

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v4
        with: 
          context: .
          file: Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ env.USERNAME }}/${{ env.REPO }}:${{ env.VERSION }} 
            